export interface RepoMetadata {
  isPrivate: boolean;
  livePreviewUrl: string | null;
  repo: string;
  sourceUrl: string;
}

export const repoMetadata: Record<string, RepoMetadata> = {
  "m-d/about": {
    repo: "micr-dev/about",
    sourceUrl: "https://github.com/micr-dev/about",
    livePreviewUrl: null,
    isPrivate: false,
  },
  anonQ: {
    repo: "Microck/anonQ",
    sourceUrl: "https://github.com/Microck/anonQ",
    livePreviewUrl: "https://micr.dev/anonq",
    isPrivate: false,
  },
  "anydesk-legacy-bin": {
    repo: "Microck/anydesk-legacy-bin",
    sourceUrl: "https://github.com/Microck/anydesk-legacy-bin",
    livePreviewUrl: "https://aur.archlinux.org/packages/anydesk-legacy-bin",
    isPrivate: false,
  },
  archie: {
    repo: "Microck/archie",
    sourceUrl: "https://github.com/Microck/archie",
    livePreviewUrl: null,
    isPrivate: true,
  },
  "ms26/bansho": {
    repo: "Microck/bansho",
    sourceUrl: "https://github.com/Microck/bansho",
    livePreviewUrl: null,
    isPrivate: false,
  },
  "bdss-club-website": {
    repo: "Microck/bdss-club-website",
    sourceUrl: "https://github.com/Microck/bdss-club-website",
    livePreviewUrl: "https://bdss-club-website.vercel.app",
    isPrivate: true,
  },
  "m-d/blog": {
    repo: "micr-dev/blog",
    sourceUrl: "https://github.com/micr-dev/blog",
    livePreviewUrl: "https://blog.micr.dev",
    isPrivate: false,
  },
  bolify: {
    repo: "Microck/boilify",
    sourceUrl: "https://github.com/Microck/boilify",
    livePreviewUrl: null,
    isPrivate: false,
  },
  "Celeste-QuartzSkin": {
    repo: "Microck/Celeste-QuarziteSkin",
    sourceUrl: "https://github.com/Microck/Celeste-QuarziteSkin",
    livePreviewUrl: "https://gamebanana.com/mods/486547",
    isPrivate: false,
  },
  chalcopyrite: {
    repo: "Microck/chalcopyrite",
    sourceUrl: "https://github.com/Microck/chalcopyrite",
    livePreviewUrl: null,
    isPrivate: true,
  },
  cinco: {
    repo: "Microck/cinco",
    sourceUrl: "https://github.com/Microck/cinco",
    livePreviewUrl: null,
    isPrivate: false,
  },
  "ms26/delvn": {
    repo: "Microck/delvn",
    sourceUrl: "https://github.com/Microck/delvn",
    livePreviewUrl: null,
    isPrivate: false,
  },
  "dialogue-textbox": {
    repo: "Microck/DialogueTextbox-Generator",
    sourceUrl: "https://github.com/Microck/DialogueTextbox-Generator",
    livePreviewUrl: "https://dialogue.micr.dev",
    isPrivate: false,
  },
  DXFtoIRL: {
    repo: "Microck/DXFtoIRL",
    sourceUrl: "https://github.com/Microck/DXFtoIRL",
    livePreviewUrl: null,
    isPrivate: false,
  },
  "elevenlabs-webui": {
    repo: "Microck/elevenlabs-webui-client",
    sourceUrl: "https://github.com/Microck/elevenlabs-webui-client",
    livePreviewUrl: null,
    isPrivate: false,
  },
  glob: {
    repo: "Microck/glob",
    sourceUrl: "https://github.com/Microck/glob",
    livePreviewUrl: "https://glob.micr.dev",
    isPrivate: false,
  },
  gitquarry: {
    repo: "Microck/gitquarry",
    sourceUrl: "https://github.com/Microck/gitquarry",
    livePreviewUrl: "http://gitquarry.micr.dev/",
    isPrivate: false,
  },
  "goofish-watcher": {
    repo: "Microck/goofish-watcher",
    sourceUrl: "https://github.com/Microck/goofish-watcher",
    livePreviewUrl: null,
    isPrivate: false,
  },
  "hermes-nightshift": {
    repo: "Microck/hermes-nightshift-glm",
    sourceUrl: "https://github.com/Microck/hermes-nightshift-glm",
    livePreviewUrl: null,
    isPrivate: false,
  },
  "ms26/indagine": {
    repo: "Microck/indagine",
    sourceUrl: "https://github.com/Microck/indagine",
    livePreviewUrl: null,
    isPrivate: false,
  },
  "ms26/jarspect": {
    repo: "Microck/jarspect",
    sourceUrl: "https://github.com/Microck/jarspect",
    livePreviewUrl: null,
    isPrivate: false,
  },
  "kagi-cli": {
    repo: "Microck/kagi-cli",
    sourceUrl: "https://github.com/Microck/kagi-cli",
    livePreviewUrl: "https://kagi.micr.dev",
    isPrivate: false,
  },
  "kefine-website": {
    repo: "Microck/kefine-website",
    sourceUrl: "https://github.com/Microck/kefine-website",
    livePreviewUrl: "https://kefine.store",
    isPrivate: true,
  },
  "m-d/micr.dev": {
    repo: "micr-dev/micr.dev",
    sourceUrl: "https://github.com/micr-dev/micr.dev",
    livePreviewUrl: "https://micr.dev",
    isPrivate: false,
  },
  "m-d/microkeebs": {
    repo: "micr-dev/microkeebs",
    sourceUrl: "https://github.com/micr-dev/microkeebs",
    livePreviewUrl: null,
    isPrivate: false,
  },
  mullgate: {
    repo: "Microck/mullgate",
    sourceUrl: "https://github.com/Microck/mullgate",
    livePreviewUrl: "https://mullgate.micr.dev",
    isPrivate: false,
  },
  nagrom: {
    repo: "Microck/nagrom",
    sourceUrl: "https://github.com/Microck/nagrom",
    livePreviewUrl: "https://microck.github.io/nagrom/",
    isPrivate: false,
  },
  onairo: {
    repo: "Microck/onairo",
    sourceUrl: "https://github.com/Microck/onairo",
    livePreviewUrl: null,
    isPrivate: false,
  },
  "opencode-studio": {
    repo: "Microck/opencode-studio",
    sourceUrl: "https://github.com/Microck/opencode-studio",
    livePreviewUrl: "https://opencode-studio.micr.dev",
    isPrivate: false,
  },
  openslate: {
    repo: "Microck/openslate",
    sourceUrl: "https://github.com/Microck/openslate",
    livePreviewUrl: null,
    isPrivate: false,
  },
  "m-d/proyectos": {
    repo: "micr-dev/proyectos",
    sourceUrl: "https://github.com/micr-dev/proyectos",
    livePreviewUrl: "https://proyectos.micr.dev",
    isPrivate: false,
  },
  protoncode: {
    repo: "Microck/protoncode",
    sourceUrl: "https://github.com/Microck/protoncode",
    livePreviewUrl: null,
    isPrivate: false,
  },
  "m-d/quarzite": {
    repo: "micr-dev/quarzite",
    sourceUrl: "https://github.com/micr-dev/quarzite",
    livePreviewUrl: null,
    isPrivate: false,
  },
  "ms26/repatrol": {
    repo: "Microck/repatrol",
    sourceUrl: "https://github.com/Microck/repatrol",
    livePreviewUrl: null,
    isPrivate: false,
  },
  scudo: {
    repo: "Microck/scudo",
    sourceUrl: "https://github.com/Microck/scudo",
    livePreviewUrl: null,
    isPrivate: false,
  },
  sincronizado: {
    repo: "Microck/sincronizado",
    sourceUrl: "https://github.com/Microck/sincronizado",
    livePreviewUrl: "https://sincronizado.micr.dev",
    isPrivate: false,
  },
  SpainGPT: {
    repo: "Microck/SpainGPT",
    sourceUrl: "https://github.com/Microck/SpainGPT",
    livePreviewUrl: null,
    isPrivate: true,
  },
  "ms26/spikehound": {
    repo: "Microck/spikehound",
    sourceUrl: "https://github.com/Microck/spikehound",
    livePreviewUrl: null,
    isPrivate: false,
  },
  squircle: {
    repo: "Microck/squircle",
    sourceUrl: "https://github.com/Microck/squircle",
    livePreviewUrl: "https://squircle.micr.dev",
    isPrivate: false,
  },
  "supabase-keepalive": {
    repo: "Microck/supabase-keep-alive",
    sourceUrl: "https://github.com/Microck/supabase-keep-alive",
    livePreviewUrl: null,
    isPrivate: false,
  },
  "t3-chat-zipper": {
    repo: "Microck/t3-chat-zipper",
    sourceUrl: "https://github.com/Microck/t3-chat-zipper",
    livePreviewUrl:
      "https://github.com/Microck/t3-chat-zipper/raw/main/t3-chat-zipper.user.js",
    isPrivate: false,
  },
  traccia: {
    repo: "Microck/traccia",
    sourceUrl: "https://github.com/Microck/traccia",
    livePreviewUrl: null,
    isPrivate: false,
  },
  tailstick: {
    repo: "Microck/tailstick",
    sourceUrl: "https://github.com/Microck/tailstick",
    livePreviewUrl: "https://tailstick.micr.dev",
    isPrivate: false,
  },
  "m-d/thinko": {
    repo: "micr-dev/thinko",
    sourceUrl: "https://github.com/micr-dev/thinko",
    livePreviewUrl: "https://thinko.micr.dev",
    isPrivate: false,
  },
  tuireel: {
    repo: "Microck/tuireel",
    sourceUrl: "https://github.com/Microck/tuireel",
    livePreviewUrl: "https://tuireel.micr.dev",
    isPrivate: false,
  },
  "m-d/tokens": {
    repo: "micr-dev/tokens",
    sourceUrl: "https://github.com/micr-dev/tokens",
    livePreviewUrl: "https://tokens.micr.dev",
    isPrivate: false,
  },
  tuneport: {
    repo: "Microck/tuneport",
    sourceUrl: "https://github.com/Microck/tuneport",
    livePreviewUrl: "https://tuneport.micr.dev",
    isPrivate: false,
  },
  tupac: {
    repo: "Microck/tupac",
    sourceUrl: "https://github.com/Microck/tupac",
    livePreviewUrl: null,
    isPrivate: false,
  },
  UndyingTerminal: {
    repo: "Microck/UndyingTerminal",
    sourceUrl: "https://github.com/Microck/UndyingTerminal",
    livePreviewUrl: "https://undyingterminal.com",
    isPrivate: false,
  },
  "upstash-keepalive": {
    repo: "Microck/upstash-keep-alive",
    sourceUrl: "https://github.com/Microck/upstash-keep-alive",
    livePreviewUrl: null,
    isPrivate: false,
  },
  vapora: {
    repo: "Microck/vapora",
    sourceUrl: "https://github.com/Microck/vapora",
    livePreviewUrl: null,
    isPrivate: false,
  },
  veyoff: {
    repo: "Microck/veyoff",
    sourceUrl: "https://github.com/Microck/veyoff",
    livePreviewUrl: null,
    isPrivate: false,
  },
  waterWAV: {
    repo: "Microck/waterWAV",
    sourceUrl: "https://github.com/Microck/waterWAV",
    livePreviewUrl: null,
    isPrivate: false,
  },
  ancla: {
    repo: "Microck/ancla",
    sourceUrl: "https://github.com/Microck/ancla",
    livePreviewUrl: null,
    isPrivate: false,
  },
  "RPi4toNAS-Guide": {
    repo: "Microck/RPi4toNAS-Guide",
    sourceUrl: "https://github.com/Microck/RPi4toNAS-Guide",
    livePreviewUrl: null,
    isPrivate: false,
  },
  "topre-ec-archive": {
    repo: "Microck/DeskthorityWiki-TopreECArchive",
    sourceUrl: "https://github.com/Microck/DeskthorityWiki-TopreECArchive",
    livePreviewUrl: "https://microck.github.io/DeskthorityWiki-TopreECArchive/",
    isPrivate: false,
  },
  YAWN60: {
    repo: "Microck/YAWN60",
    sourceUrl: "https://github.com/Microck/YAWN60",
    livePreviewUrl: null,
    isPrivate: false,
  },
  "camofox-mcp": {
    repo: "Microck/camofox-browser-mcp",
    sourceUrl: "https://github.com/Microck/camofox-browser-mcp",
    livePreviewUrl: "https://www.npmjs.com/package/camofox-browser-mcp",
    isPrivate: false,
  },
  "catbox-mcp": {
    repo: "Microck/catbox-mcp",
    sourceUrl: "https://github.com/Microck/catbox-mcp",
    livePreviewUrl: null,
    isPrivate: false,
  },
  "chatgpt-webui-mcp": {
    repo: "Microck/chatgpt-webui-mcp",
    sourceUrl: "https://github.com/Microck/chatgpt-webui-mcp",
    livePreviewUrl: null,
    isPrivate: false,
  },
  "discord-self-mcp": {
    repo: "Microck/discord.py-self-mcp",
    sourceUrl: "https://github.com/Microck/discord.py-self-mcp",
    livePreviewUrl: "https://www.npmjs.com/package/discord-selfbot-mcp",
    isPrivate: false,
  },
  "kagi-mcp": {
    repo: "Microck/kagi-mcp",
    sourceUrl: "https://github.com/Microck/kagi-mcp",
    livePreviewUrl: "https://kagi.micr.dev",
    isPrivate: false,
  },
  "namecheap-mcp": {
    repo: "Microck/namecheap-webui-mcp",
    sourceUrl: "https://github.com/Microck/namecheap-webui-mcp",
    livePreviewUrl: null,
    isPrivate: false,
  },
  "perplexity-mcp": {
    repo: "Microck/perplexity-webui-mcp",
    sourceUrl: "https://github.com/Microck/perplexity-webui-mcp",
    livePreviewUrl: null,
    isPrivate: false,
  },
  "claude-skills": {
    repo: "Microck/ordinary-claude-skills",
    sourceUrl: "https://github.com/Microck/ordinary-claude-skills",
    livePreviewUrl: "https://microck.github.io/ordinary-claude-skills/",
    isPrivate: false,
  },
  "gsap-skills": {
    repo: "Microck/gsap-skills",
    sourceUrl: "https://github.com/Microck/gsap-skills",
    livePreviewUrl: null,
    isPrivate: false,
  },
  "seedance-skills": {
    repo: "Microck/seedance-skills",
    sourceUrl: "https://github.com/Microck/seedance-skills",
    livePreviewUrl: null,
    isPrivate: false,
  },
};
